name: Linters

on:
  pull_request:

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    if: ${{ github.event.pusher.name != 'github-actions[bot]' }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Commitsar check
      uses: aevea/commitsar@v0.17.0

